name: Build and Deploy to GCP

on:
  push:
    branches:
        - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE: static-site

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # GCP CLI 설정
    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Docker가 gcloud 명령줄 도구를 사용하여 인증할 수 있도록 Docker를 구성하는 단계
    - run: |-
        gcloud --quiet auth configure-docker
    
    # GCP 자격 증명을 가져오는 단계
    - name: google auth
      id: "auth"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    # Docker Image Build
    - name: Build
      run: |-
        docker build \
        --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
        --build-arg GITHUB_SHA="$GITHUB_SHA" \
        --build-arg GITHUB_REF="$GITHUB_REF" \
        .

    # 빌드된 Docker Image를 Google Container Registry로 Push하는 단계
    - name: Publish
      run: |-
        docker push "asia-northeast3-docker.pkg.dev/$PROJECT_ID/docker-repo/$IMAGE:$GITHUB_SHA"
    
    # 빌드된 Docker Image를 GCP로 배포하는 단계
    - name: 'Deploy to Cloud Run'
      run: |
        gcloud run deploy fastapp-service --image=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA \
        --platform=managed \
        --region=asia-northeast3 \
        --allow-unauthenticated